events { worker_connections 1024; }
http {
    resolver 127.0.0.11 valid=5s;

    map $remote_addr $validated_xff {
        172.25.0.2           $http_x_forwarded_for;
        172.25.0.3           $http_x_forwarded_for;
        default              "";
    }

    map $validated_xff $final_xff {
        ""       $remote_addr;
        default  "${validated_xff}, $remote_addr";
    }

    server {
        listen 80;
        
        proxy_set_header X-Forwarded-For $final_xff;

        location /app {
            proxy_pass http://app:80;
        }
    }
}
